controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: '/api'
api_login_check:
    path: /api/login_check
github_connect:
    path: /auth/github
    controller: App\Controller\GithubController::connectAction

github_check:
    path: /auth/github/check
    controller: App\Controller\GithubController::connectCheckAction
